"""empty message

Revision ID: 4a0071d2bb86
Revises: fe7249a35ff7
Create Date: 2020-04-17 15:53:22.526222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a0071d2bb86'
down_revision = 'fe7249a35ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'type')
    # ### end Alembic commands ###
