"""empty message

Revision ID: 84c1aefcd32b
Revises: 4a0071d2bb86
Create Date: 2020-04-18 14:27:13.133905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c1aefcd32b'
down_revision = '4a0071d2bb86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'path')
    # ### end Alembic commands ###
