"""empty message

Revision ID: de533185ea5a
Revises: 84c1aefcd32b
Create Date: 2020-07-10 10:16:51.347024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de533185ea5a'
down_revision = '84c1aefcd32b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('cover', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'cover')
    # ### end Alembic commands ###
