"""empty message

Revision ID: e7ac35f79158
Revises: de533185ea5a
Create Date: 2020-07-22 15:22:47.220469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ac35f79158'
down_revision = 'de533185ea5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebook_type_ref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ebook_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ebook_type_ref')
    # ### end Alembic commands ###
