"""empty message

Revision ID: fe7249a35ff7
Revises: 3307800e69b8
Create Date: 2020-04-16 15:01:54.912046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7249a35ff7'
down_revision = '3307800e69b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actor', 'type')
    # ### end Alembic commands ###
